Blast\Bundle\UtilsBundle\Entity\CustomFilter:
    type: entity
    repositoryClass: Blast\Bundle\UtilsBundle\Repository\CustomFilterRepository
    blast:
        loggable:     true
    fields:
        name:
            type: string
            length: 255
        routeName:
            type: string
            length: 255
        routeParameters:
            type: text
            nullable: true
        filterParameters:
            type: text
            nullable: true
    manyToOne:
        user:
            targetEntity: Blast\Bundle\CoreBundle\Model\UserInterface
