# Entity to persist select choices lists
Blast\Bundle\UtilsBundle\Entity\SelectChoice:
    type: entity
    blast:
        loggable:     true
    fields:
        label:
            type:     string
            nullable: false
        value:
            type:     string
            nullable: false
